# This file is part of LTSP, https://ltsp.github.io
# Copyright 2019 the LTSP team, see AUTHORS
# SPDX-License-Identifier: GPL-3.0-or-later

# Add live (overlay) support to initramfs-tools

main() {
    warn "Starting $LTSP_TOOL"
    writeable || overlay_root
    patch_networking
    patch_root
    # Move ltsp to /run to make it available after pivot_root
    mv /ltsp /run/ltsp
    # warn "Here's a shell before pivot:\n"; /bin/sh
}

writeable() {
    chroot "$rootmnt" /usr/bin/test -w / && return 0
    mount -o remount,rw "$rootmnt"
    chroot "$rootmnt" /usr/bin/test -w / && return 0
    return 1
}

modprobe_overlay() {
    grep -q overlay /proc/filesystems &&
        return 0
    modprobe overlay &&
        grep -q overlay /proc/filesystems &&
        return 0
    insmod "$rootmnt/lib/modules/$(uname -r)/kernel/fs/overlayfs/overlay.ko" &&
        grep -q overlay /proc/filesystems &&
        return 0
    panic "Couldn't modprobe overlay!"
}

overlay_root() {
    modprobe_overlay
    mkdir -p /run/initramfs/rofs /run/initramfs/cow
    mount -o move "$rootmnt" /run/initramfs/rofs
    mount -t tmpfs -o mode=0755 tmpfs /run/initramfs/cow
    mkdir -p /run/initramfs/cow/up /run/initramfs/cow/work
    mount -t overlay -o upperdir=/run/initramfs/cow/up,lowerdir=/run/initramfs/rofs,workdir=/run/initramfs/cow/work overlay "$rootmnt"
}

patch_networking() {
    # TODO: this is initramfs-tools specific
    grep -Eqw 'root=/dev/nbd.*|root=/dev/nfs' /proc/cmdline || return 0
    . /run/net-*.conf
    # prohibit network-manager from messing with the boot interface
    printf "%s" "[keyfile]
unmanaged-devices=interface-name:$DEVICE
" > "$rootmnt/etc/NetworkManager/conf.d/ltsp.conf"
    printf "%s" "# Dynamically generated by LTSP.
auto lo
iface lo inet loopback

auto $DEVICE
iface $DEVICE inet manual
" > "$rootmnt/etc/network/interfaces"
    # Never ifdown anything. Safer! :P
    ln -sf ../bin/true "$rootmnt/sbin/ifdown"
}

patch_root() {
    printf "# Empty fstab generated by LTSP.\n" > "$rootmnt/etc/fstab"
    if grep -qs 'AutomaticLoginEnable.*=' "$rootmnt/etc/gdm3/daemon.conf"; then
        sed -e 's/.*AutomaticLoginEnable[ ]*=.*/AutomaticLoginEnable = True/' \
            -e 's/.*AutomaticLogin[ ]*=.*/AutomaticLogin = administrator/' \
            -i "$rootmnt/etc/gdm3/daemon.conf"
    fi
    # return 0
    # Test automatic reboots, for stability!
    printf '#!/bin/sh
echo "This is RC LOCAL!" >&2
echo "This is RC LOCAL!"
# sleep 30  #  Cups does not like quick reboots and delays
# Systemd unit "Make remote CUPS printers available locally",
# sometimes needs 25 secs on NBD, 60 on NFS, with timeout=90
# reboot
' > "$rootmnt/etc/rc.local"
    chmod +x "$rootmnt/etc/rc.local"
}

