# This file is part of LTSP, https://ltsp.github.io
# Copyright 2019 the LTSP team, see AUTHORS
# SPDX-License-Identifier: GPL-3.0-or-later

# TODO: this only handles Debian-based distributions currently
networking_main() {
    local var

    grep -Eqw 'root=/dev/nbd.*|root=/dev/nfs' /proc/cmdline ||
        return 0
    re test "DEVICE=$DEVICE" != "DEVICE="
    rw rm -rf /run/netplan /etc/netplan /lib/systemd/system-generators/netplan

    # Prohibit network-manager from managing the boot interface
    test -d /etc/NetworkManager/conf.d &&
        printf "%s" "[keyfile]
unmanaged-devices=interface-name:$DEVICE
" > /etc/NetworkManager/conf.d/ltsp.conf

    # Prohibit ifupdown from managing the boot interface
    test -f /etc/network/interfaces &&
        printf "%s" "# Generated by \`ltsp init\`, see man:ltsp(8)
# interfaces(5) file used by ifup(8) and ifdown(8)
auto lo
iface lo inet loopback

auto $DEVICE
iface $DEVICE inet manual
" > /etc/network/interfaces

    # Never ifdown anything. Safer!
    test ! -x /sbin/ifdown ||
        rw ln -sf ../bin/true /sbin/ifdown

    # TODO: fix $DNS_SERVER; but remember DNS won't work until systemd runs
    rw rm -f "/etc/resolv.conf"
    for var in $DNS_SERVER; do
        rw echo "nameserver $var" >>/etc/resolv.conf
    done
    rw sed "s|\bserver\b|replaced-server|g" -i /etc/hosts
    rw printf "$SERVER\tserver\n" >>/etc/hosts
}
