.TH ltsp\-kernel(8) \- copy kernel from image to TFTP
.SH SYNOPSIS
.PP
\fB\fCltsp\-kernel\fR [\fB\fC\-h\fR] [\fB\fC\-i\fR=\fIinitrd\fP] [\-k=\fIkernel\fP] [\-n=\fIname\fP] [\-p=\fIpartition\fP] [\fIimage\fP]

.SH DESCRIPTION
.PP
Copy vmlinuz and initrd.img from an image or directory to TFTP.
If \fB\fCimage\fR is unspecified, process all of them.
For simplicity, only directories (chroots) and raw images are supported,
either full filesystems (ext4 etc) or full disks (VMs). The may be sparse
to preserve space. Don't use a separate /boot nor LVM in disk images.
The targets will always be named vmlinuz and initrd.img to simplify boot.ipxe.

.SH OPTIONS
.PP
\fB\fC\-h\fR, \fB\fC\-\-help\fR
    Display a help message.

.PP
\fB\fC\-i\fR, \fB\fC\-\-initrd\fR=\fIpath\fP
    Specify the initrd path; try to autodetect if undefined.

.PP
\fB\fC\-k\fR, \fB\fC\-\-kernel\fR=\fIpath\fP:
    Specify the kernel path; try to autodetect if undefined.

.PP
\fB\fC\-n\fR, \fB\fC\-\-name\fR=\fIname\fP:
    Specify the image name; otherwise it defaults to the (parent,
    for files) directory name; or to `uname \-m` in the chrootless case.

.PP
\fB\fC\-p\fR, \fB\fC\-\-partition\fR=\fInumber\fP:
    Image is a raw disk; the kernel/initrd is in partition \fB\fCNUMBER\fR\&.

.PP
\fB\fC\-\-version\fR:
    Display the version information.

.SH FILES
.SH ENVIRONMENT
.SH EXAMPLES
.PP
sudo \~/bin/ltsp\-kernel \-p 1 /srv/ltsp/bionic\-mate\-sch32/bionic\-mate\-sch32\-flat.vmdk
TODO: implement ltsp\-chroot as well; for quick things like looking up the kernel name.
TODO: document that we allow defining parameters in the environment, e.g.
    partition=1 ltsp\-kernel image
" "$0"

.SH COPYRIGHT
.PP
Copyright 2019 the LTSP team, see 
\[la]https://github.com/ltsp/ltsp/graphs/contributors\[ra]\&.

.SH SEE ALSO
.PP
ltsp(8), ltsp\-image(8)
