#!/bin/sh
# This file is part of LTSP, https://ltsp.github.io
# Copyright 2019 the LTSP team, see AUTHORS
# SPDX-License-Identifier: GPL-3.0-or-later

# LTSP_PHASE=init
# Override /sbin/init to run some LTSP code, then restore the real init.
# I think it can't be just a symlink to ltsp.sh like the other tools,
# because of initramfs init validation / broken symlink at that point.

echo "This is init-ltsp $*, type exit to continue booting"
rm /sbin/init
mv /sbin/init.real /sbin/init
bash
exec /sbin/init
